import {assess,nextRoute} from './logic.js';
const app=document.querySelector('#app');
const initial=()=>({goal:'',interest:'',forWhom:'',age:'',location:'',diagnosis:'',diagnosisAge:'',familyStatus:'',relatives:[],variant:'',prior:''});
let a=initial(),step='home';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opts=(key,list)=>`<div class="options" role="group" aria-label="Choose an answer">${list.map(([v,label,sub])=>`<button class="option ${a[key]===v?'selected':''}" data-key="${key}" data-value="${v}" aria-pressed="${a[key]===v}"><span>${label}${sub?`<small>${sub}</small>`:''}</span><span class="radio" aria-hidden="true"></span></button>`).join('')}</div>`;
const field=(label,key,type='text',extra='')=>`<label class="field">${label}<input data-field="${key}" type="${type}" value="${esc(a[key])}" ${extra}></label>`;
const sel=(label,key,list,value)=>`<label class="field">${label}<select data-field="${key}">${list.map(([v,t])=>`<option value="${v}" ${value===v?'selected':''}>${t}</option>`).join('')}</select></label>`;
const standard=[['yes','Yes'],['no','No'],['unknown','I’m not sure']];
function shell(title,sub,body,n=1){return `<div class="layout"><aside class="sidebar"><div class="eyebrow">YOUR GENETIC TESTING EXPLORER</div><ol class="steps">${['Your starting point','Your health & family','Your options'].map((s,i)=>`<li class="${n===i+1?'active':''}"><b>${i+1}</b>${s}</li>`).join('')}</ol><p class="aside-note">You don’t need all the answers.<br><br>“I’m not sure” helps us identify what a genetic counsellor can clarify.</p></aside><section class="form-area"><div class="progress"><div class="progress-${n}"></div></div><div class="eyebrow">${n===1?'LET’S FIND YOUR STARTING POINT':'BREAST CANCER GENETICS'}</div><h1 tabindex="-1">${title}</h1><p class="muted">${sub}</p>${body}<p class="error" id="error" role="alert"></p><div class="actions"><button class="text-button" id="back">← Back</button><button class="primary" id="next">Continue <span>→</span></button></div></section></div>`}
function go(s){step=s;render();window.scrollTo(0,0);app.querySelector('h1')?.focus({preventScroll:true})}
function relatives(){return a.relatives.map((r,i)=>`<div class="relative"><div class="relative-title"><strong>Relative ${i+1}</strong><button class="text-button" data-remove="${i}" aria-label="Remove relative ${i+1}">Remove</button></div><div class="inline-fields">${sel('Relationship',`r${i}.relationship`,[['','Choose a relative'],['mother','Mother'],['father','Father'],['sister','Sister'],['brother','Brother'],['grandmother','Grandmother'],['grandfather','Grandfather'],['aunt','Aunt'],['uncle','Uncle'],['daughter','Daughter'],['son','Son'],['other','Other biological relative']],r.relationship)}${sel('Side of family',`r${i}.side`,[['','Choose'],['maternal','Mother’s side'],['paternal','Father’s side'],['both','Both / immediate family'],['unknown','Not sure']],r.side)}${sel('Cancer type',`r${i}.cancer`,[['','Choose'],['breast','Breast'],['ovarian','Ovarian'],['other','Another cancer'],['unknown','Not sure']],r.cancer)}<label class="field">Age at diagnosis, if known<input type="number" min="0" max="120" data-field="r${i}.age" value="${esc(r.age)}" placeholder="Leave blank if unsure"></label></div></div>`).join('')}
const labels={family:'A condition in my family',health:'My own health',pregnancy:'Planning a pregnancy',medication:'Medication response',general:'General health or screening',unsure:'Not sure yet',myself:'Myself',child:'My child',other:'Someone else',unknown:'Not sure',yes:'Yes',no:'No'};
function facts(){return [`Purpose: ${labels[a.goal]||'Not specified'}`,`Who: ${labels[a.forWhom]||a.forWhom}; age: ${a.age||'unknown'}; location: ${a.location||'unknown'}`,`Personal breast cancer diagnosis: ${labels[a.diagnosis]||'Not sure'}${a.diagnosisAge?`; age at diagnosis: ${a.diagnosisAge}`:''}`,`Family history: ${labels[a.familyStatus]||'Not sure'}`,...a.relatives.map(r=>`${r.relationship} (${r.side}): ${r.cancer} cancer; diagnosed ${r.age?`at ${r.age}`:'at an unknown age'}`),`Confirmed inherited family variant: ${labels[a.variant]||'Not sure'}`,`Previous genetic testing: ${labels[a.prior]||'Not sure'}`]}
function result(){const r=assess(a);return `<div class="result-head"><span class="pill">POSSIBLE PATHWAYS · NOT AN ELIGIBILITY DECISION</span><h1 tabindex="-1">${r.headline}</h1><p class="muted">${r.family?'You’ve reported cancer in your biological family. A genetic counsellor can help put that history into context.':'A genetic counsellor can help you understand what testing may—and may not—tell you.'}</p></div><div class="notice"><strong>What may be relevant</strong><br>${r.scope?'An assessment of inherited breast cancer risk, with discussion of whether a hereditary cancer panel or a targeted family-variant test is appropriate.':'A tailored consultation. This prototype does not evaluate children, other people’s eligibility or funding outside Australia.'} This explores inherited risk, not mammograms or a diagnosis of breast cancer.</div><div class="cards">${[['01 / MEDICARE','Needs further assessment',r.medicare],['02 / PUBLIC SERVICES',r.scope&&(r.family||r.personal||r.known)?'A possible referral route':'Needs more information',r.public],['03 / PRIVATE TESTING','Self-funded options',r.private]].map(([n,h,p])=>`<article class="card"><span class="number">${n}</span><h3>${h}</h3><p>${p}</p></article>`).join('')}</div><div class="consult"><div><h2>Make sense of your next step.</h2><p>A genetic counsellor can review your history, discuss testing and help clarify funding or referral options.</p></div><button class="primary" id="consult">Talk to a genetic counsellor ↗</button></div><div class="summary"><h3>What would help clarify your options</h3><ul>${r.flags.map(x=>`<li>${x}</li>`).join('')}</ul></div><details open><summary>Your answers</summary><ul>${facts().map(x=>`<li>${esc(x)}</li>`).join('')}</ul><button class="text-button" id="edit">Edit answers</button></details><details><summary>Where this guidance comes from</summary><p>Supplied eligibility catalogue dated 7 October 2026: ${r.refs.join(', ')}. These are source summaries, not independently verified current Medicare descriptors. Public clinic criteria and laboratory prices are not established here. A rebate does not necessarily mean a free test.</p><p>Family history alone has not been converted into a genetic risk score. Missing information is treated as unknown.</p></details><div class="actions"><button class="secondary" id="download">Download my summary ↓</button><button class="text-button" id="finish-reset">Start again</button></div>`}
function render(){
 if(step==='home')app.innerHTML=`<section class="hero"><div><div class="eyebrow">MADE FOR YOUR NEXT STEP</div><h1>Your questions.<br>Your genetics.<br>A place to start.</h1><p class="intro muted">Explore genetic testing that may be relevant to you—and the pathways that could help you access it.</p><button class="primary" id="begin">Explore my options <span>↗</span></button><p class="muted intro-note">A few questions. No account needed.</p></div><div class="art" aria-hidden="true"><div class="rings"><i></i><i></i><i></i></div><h2>A little clarity.<br>A next step<br>made for you.</h2><small>YOUR STORY IS THE STARTING POINT.</small></div></section><div class="trust"><span>◌ Guided by your personal and family history</span><span>◌ Answers stay in this browser tab</span><span>◌ A starting point for a GC conversation</span></div><div class="notice">This prototype currently explores <strong>hereditary breast cancer</strong>. Other interests can be selected, but their detailed pathways are not built yet.</div>`;
 if(step==='goal')app.innerHTML=shell('What brings you here?','Choose the main thing you’d like help understanding.',opts('goal',[['family','A condition in my family','Understand an inherited risk'],['health','My own health','Explore a diagnosis or health concern'],['pregnancy','Planning a pregnancy','Learn about reproductive testing'],['medication','Medication response','Understand genetic testing for medicines'],['general','General health or screening','Explore what testing could tell me'],['unsure','I’m not sure yet','Help me find a starting point']]));
 if(step==='interest')app.innerHTML=shell('Anything specific in mind?','Choose a condition or area. You don’t need to know the name of a genetic test.',opts('interest',[['breast','Breast cancer','Inherited risk · BRCA and related testing'],['cancer','Another inherited cancer'],['carrier','Pregnancy and carrier screening'],['heart','Heart or cholesterol conditions'],['rare','Rare or undiagnosed conditions'],['pgx','Medication-response testing'],['other','Something else'],['unsure','I don’t have a test in mind']]));
 if(step==='clarify')app.innerHTML=shell('Where would you like to begin?','You can explore the available breast cancer pathway, or take your broader question to a genetic counsellor.',opts('clarification',[['breast','Breast cancer in me or my family'],['general','A broader genetics conversation']]));
 if(step==='who')app.innerHTML=shell('Who are you exploring for?','The detailed prototype supports adults answering for themselves in Australia.',opts('forWhom',[['myself','Myself'],['child','My child'],['other','Someone else']])+field('Age of the person being considered','age','number','min="0" max="120" inputmode="numeric"')+sel('Where do they live?','location',[['','Select a location'],['Australia','Australia'],['Other','Outside Australia'],['Unknown','Not sure']],a.location));
 if(step==='diagnosis')app.innerHTML=shell('Have you had breast cancer?','This helps distinguish testing after a diagnosis from testing for an inherited family risk.',opts('diagnosis',standard)+(a.diagnosis==='yes'?field('Age at diagnosis, if known','diagnosisAge','number','min="0" max="120"'):'')+'<div class="notice">Looking for a mammogram or concerned about a new breast change? This genetic testing explorer cannot assess that. Please discuss it with your healthcare professional.</div>',2);
 if(step==='family')app.innerHTML=shell('Has anyone in your biological family had cancer?','Include both sides of your family. Details about relatives who have died can still be recorded. Unknown ages are okay.',opts('familyStatus',standard)+(a.familyStatus==='yes'?relatives()+'<button class="secondary" id="add-relative">+ Add a relative</button>':''),2);
 if(step==='variant')app.innerHTML=shell('Has an inherited gene variant been found in your family?','For example, a confirmed BRCA1 or BRCA2 result. A cancer diagnosis by itself does not tell us whether a variant was found.',opts('variant',[['yes','Yes, an inherited variant was confirmed'],['no','No known inherited variant'],['unknown','I’m not sure / reports aren’t available']]),2);
 if(step==='prior')app.innerHTML=shell('Have you had genetic testing before?','Previous testing can affect which test or funding pathway is relevant. A mammogram is not a genetic test.',opts('prior',standard),2);
 if(step==='review')app.innerHTML=shell('Does this look right?','Check your answers before exploring possible pathways. Nothing is sent to a clinic.',`<div class="summary"><ul>${facts().map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><p class="muted">The result uses the supplied research catalogue. It does not confirm eligibility, choose a test for you or guarantee funding.</p>`,3);
 if(step==='result')app.innerHTML=result();
 if(step==='unavailable')app.innerHTML=`<div class="compact"><span class="pill">YOUR STARTING POINT</span><h1 tabindex="-1">You don’t need to have a test in mind.</h1><p class="muted">A genetic counsellor can help clarify your question and whether genetic testing might be useful.</p><div class="notice">This area isn’t assessed in the prototype yet. That does not mean testing or funding is unavailable.</div><div class="consult"><div><h2>Start with a conversation.</h2><p>Talk through your goals, family history and possible next steps.</p></div><button class="primary" id="consult">Consultation preview ↗</button></div><div class="actions"><button class="text-button" id="back">← Back</button><button class="secondary" id="try-breast">Explore breast cancer</button></div></div>`;
 bind();
}
function error(t){document.querySelector('#error').textContent=t}
const sequence=['home','goal','interest','who','diagnosis','family','variant','prior','review','result'];
function next(){
 if(step==='goal'){if(!a.goal)return error('Choose an option, including “I’m not sure”.');return go('interest')}
 if(step==='interest'){if(!a.interest)return error('Choose an area or “I don’t have a test in mind”.');const r=nextRoute(a);return go(r==='breast'?'who':r)}
 if(step==='clarify'){if(!a.clarification)return error('Choose where you’d like to begin.');if(a.clarification==='breast'){a.interest='breast';return go('who')}return go('unavailable')}
 if(step==='who'){if(!a.forWhom||a.age===''||!a.location)return error('Please add who this is for, an age and a location.');if(!Number.isInteger(Number(a.age))||Number(a.age)<0||Number(a.age)>120)return error('Please enter an age between 0 and 120.');if(a.forWhom!=='myself'||Number(a.age)<18||a.location!=='Australia')return go('result')}
 if(step==='diagnosis'){if(!a.diagnosis)return error('Please select an answer.');if(a.diagnosisAge && (Number(a.diagnosisAge)<0||Number(a.diagnosisAge)>Number(a.age)))return error('Age at diagnosis cannot exceed your current age.')}
 if(step==='family'){if(!a.familyStatus)return error('Please select an answer.');if(a.familyStatus==='yes'&&(!a.relatives.length||a.relatives.some(r=>!r.relationship||!r.side||!r.cancer)))return error('Add at least one relative and choose the relationship, side and cancer type. “Not sure” is available.');if(a.relatives.some(r=>r.age!==''&&(!Number.isInteger(Number(r.age))||Number(r.age)<0||Number(r.age)>120)))return error('Use an age between 0 and 120, or leave it blank.')}
 if(step==='variant'&&!a.variant)return error('Please select an answer.');if(step==='prior'&&!a.prior)return error('Please select an answer.');go(sequence[sequence.indexOf(step)+1]);
}
function back(){if(['clarify','unavailable','who'].includes(step))return go('interest');go(sequence[Math.max(0,sequence.indexOf(step)-1)])}
function modal(content){document.querySelector('#modal-content').innerHTML=content;document.querySelector('#modal').showModal()}
function reset(){a=initial();go('home')}
function download(){const r=assess(a);const text=`MADE GENETICS — CONSULTATION SUMMARY\nPrototype: document-based pathways, not confirmed eligibility\n\n${facts().join('\n')}\n\nMedicare: ${r.medicare}\nPublic services: ${r.public}\nPrivate: ${r.private}\n\nTo clarify:\n${r.flags.join('\n')}\n\nSource rules: ${r.refs.join(', ')}. Supplied catalogue dated 7 October 2026; not independently verified current guidance.\nNo booking or referral has been submitted.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download='made-genetics-summary.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function bind(){app.querySelectorAll('[data-key]').forEach(el=>el.onclick=()=>{a[el.dataset.key]=el.dataset.value;if(el.dataset.key==='familyStatus'&&el.dataset.value!=='yes')a.relatives=[];if(el.dataset.key==='diagnosis'&&el.dataset.value!=='yes')a.diagnosisAge='';render()});app.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>{const k=el.dataset.field;if(k.startsWith('r')&&k.includes('.')){const [i,f]=k.slice(1).split('.');a.relatives[Number(i)][f]=el.value}else a[k]=el.value});
const on=(id,fn)=>{const e=document.getElementById(id);if(e)e.onclick=fn};on('begin',()=>go('goal'));on('next',next);on('back',back);on('add-relative',()=>{a.relatives.push({relationship:'',side:'',cancer:'',age:''});render()});app.querySelectorAll('[data-remove]').forEach(e=>e.onclick=()=>{a.relatives.splice(Number(e.dataset.remove),1);render()});on('edit',()=>go('who'));on('try-breast',()=>{a.interest='breast';go('who')});on('download',download);on('finish-reset',reset);on('consult',()=>modal('<span class="pill">CONSULTATION PREVIEW</span><h2>A next step with a genetic counsellor.</h2><p>A consultation can help review your family history, discuss testing and clarify referral or funding options.</p><div class="notice">Booking is not connected in this prototype. No appointment or referral has been made, and no answers have been sent.</div><p>Consultation fees and the booking service will be shown here once confirmed.</p>'));
}
document.getElementById('restart').onclick=()=>modal('<h2>Start again?</h2><p>This will clear the answers in this tab.</p><button class="primary" id="confirm-reset">Clear and restart</button>');document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='confirm-reset'){document.getElementById('modal').close();reset()}});document.getElementById('close-modal').onclick=()=>document.getElementById('modal').close();document.getElementById('privacy').onclick=()=>modal('<h2>Your answers stay with you.</h2><p>This prototype holds answers only in this tab’s memory. It does not send them to a server, save them in browser storage or include them in the address bar. Refreshing or closing the page clears them.</p><p>If you download a summary, it contains the health details you entered. It stays wherever you save it. Standard hosting access logs may record page requests, but the app does not send your answers.</p>');render();
