import {reproductiveDefaults,isReproductive,wants,reproductiveSteps,validateReproductive,reproductiveFacts,assessReproductive} from './reproductive.js';
import {assess,nextRoute} from './logic.js';
const app=document.querySelector('#app');
const initial=()=>({...reproductiveDefaults(),goal:'',interest:'',forWhom:'',age:'',location:'',diagnosis:'',diagnosisAge:'',familyStatus:'',relatives:[],variant:'',prior:''});
let a=initial(),step='home';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opts=(key,list)=>`<div class="options" role="group" aria-label="Choose an answer">${list.map(([v,label,sub])=>`<button class="option ${a[key]===v?'selected':''}" data-key="${key}" data-value="${v}" aria-pressed="${a[key]===v}"><span>${label}${sub?`<small>${sub}</small>`:''}</span><span class="radio" aria-hidden="true"></span></button>`).join('')}</div>`;
const field=(label,key,type='text',extra='')=>`<label class="field">${label}<input data-field="${key}" type="${type}" value="${esc(a[key])}" ${extra}></label>`;
const sel=(label,key,list,value)=>`<label class="field">${label}<select data-field="${key}">${list.map(([v,t])=>`<option value="${v}" ${value===v?'selected':''}>${t}</option>`).join('')}</select></label>`;
const standard=[['yes','Yes'],['no','No'],['unknown','I’m not sure']];
function shell(title,sub,body,n=1){return `<div class="layout"><aside class="sidebar"><div class="eyebrow">YOUR GENETIC TESTING EXPLORER</div><ol class="steps">${['Your starting point','Your health & family','Your options'].map((s,i)=>`<li class="${n===i+1?'active':''}"><b>${i+1}</b>${s}</li>`).join('')}</ol><p class="aside-note">You don’t need all the answers.<br><br>“I’m not sure” helps us identify what a genetic counsellor can clarify.</p></aside><section class="form-area"><div class="progress"><div class="progress-${n}"></div></div><div class="eyebrow">${n===1?'LET’S FIND YOUR STARTING POINT':(isReproductive(a)?'REPRODUCTIVE GENETICS':'BREAST CANCER GENETICS')}</div><h1 tabindex="-1">${title}</h1><p class="muted">${sub}</p>${body}<p class="error" id="error" role="alert"></p><div class="actions"><button class="text-button" id="back">← Back</button><button class="primary" id="next">Continue <span>→</span></button></div></section></div>`}
function go(s){step=s;render();window.scrollTo(0,0);app.querySelector('h1')?.focus({preventScroll:true})}
function relatives(){return a.relatives.map((r,i)=>`<div class="relative"><div class="relative-title"><strong>Relative ${i+1}</strong><button class="text-button" data-remove="${i}" aria-label="Remove relative ${i+1}">Remove</button></div><div class="inline-fields">${sel('Relationship',`r${i}.relationship`,[['','Choose a relative'],['mother','Mother'],['father','Father'],['sister','Sister'],['brother','Brother'],['grandmother','Grandmother'],['grandfather','Grandfather'],['aunt','Aunt'],['uncle','Uncle'],['daughter','Daughter'],['son','Son'],['other','Other biological relative']],r.relationship)}${sel('Side of family',`r${i}.side`,[['','Choose'],['maternal','Mother’s side'],['paternal','Father’s side'],['both','Both / immediate family'],['unknown','Not sure']],r.side)}${sel('Cancer type',`r${i}.cancer`,[['','Choose'],['breast','Breast'],['ovarian','Ovarian'],['other','Another cancer'],['unknown','Not sure']],r.cancer)}<label class="field">Age at diagnosis, if known<input type="number" min="0" max="120" data-field="r${i}.age" value="${esc(r.age)}" placeholder="Leave blank if unsure"></label></div></div>`).join('')}
const labels={family:'A condition in my family',health:'My own health',pregnancy:'Pregnancy, fertility or family planning',medication:'Medication response',general:'General health or screening',unsure:'Not sure yet',myself:'Myself',child:'My child',other:'Someone else',unknown:'Not sure',yes:'Yes',no:'No'};
function facts(){if(isReproductive(a))return [`Purpose: ${labels[a.goal]||'Not specified'}`,`Who: ${labels[a.forWhom]||a.forWhom}; age: ${a.age||'unknown'}; location: ${a.location||'unknown'}`,...reproductiveFacts(a)];return [`Purpose: ${labels[a.goal]||'Not specified'}`,`Who: ${labels[a.forWhom]||a.forWhom}; age: ${a.age||'unknown'}; location: ${a.location||'unknown'}`,`Personal breast cancer diagnosis: ${labels[a.diagnosis]||'Not sure'}${a.diagnosisAge?`; age at diagnosis: ${a.diagnosisAge}`:''}`,`Family history: ${labels[a.familyStatus]||'Not sure'}`,...a.relatives.map(r=>`${r.relationship} (${r.side}): ${r.cancer} cancer; diagnosed ${r.age?`at ${r.age}`:'at an unknown age'}`),`Confirmed inherited family variant: ${labels[a.variant]||'Not sure'}`,`Previous genetic testing: ${labels[a.prior]||'Not sure'}`]}
function result(){const r=assess(a);return `<div class="result-head"><span class="pill">POSSIBLE PATHWAYS · NOT AN ELIGIBILITY DECISION</span><h1 tabindex="-1">${r.headline}</h1><p class="muted">${r.family?'You’ve reported cancer in your biological family. A genetic counsellor can help put that history into context.':'A genetic counsellor can help you understand what testing may—and may not—tell you.'}</p></div><div class="notice"><strong>What may be relevant</strong><br>${r.scope?'An assessment of inherited breast cancer risk, with discussion of whether a hereditary cancer panel or a targeted family-variant test is appropriate.':'A tailored consultation. This prototype does not evaluate children, other people’s eligibility or funding outside Australia.'} This explores inherited risk, not mammograms or a diagnosis of breast cancer.</div><div class="cards">${[['01 / MEDICARE','Needs further assessment',r.medicare],['02 / PUBLIC SERVICES',r.scope&&(r.family||r.personal||r.known)?'A possible referral route':'Needs more information',r.public],['03 / PRIVATE TESTING','Self-funded options',r.private]].map(([n,h,p])=>`<article class="card"><span class="number">${n}</span><h3>${h}</h3><p>${p}</p></article>`).join('')}</div><div class="consult"><div><h2>Make sense of your next step.</h2><p>A genetic counsellor can review your history, discuss testing and help clarify funding or referral options.</p></div><button class="primary" id="consult">Talk to a genetic counsellor ↗</button></div><div class="summary"><h3>What would help clarify your options</h3><ul>${r.flags.map(x=>`<li>${x}</li>`).join('')}</ul></div><details open><summary>Your answers</summary><ul>${facts().map(x=>`<li>${esc(x)}</li>`).join('')}</ul><button class="text-button" id="edit">Edit answers</button></details><details><summary>Where this guidance comes from</summary><p>Supplied eligibility catalogue dated 7 October 2026: ${r.refs.join(', ')}. These are source summaries, not independently verified current Medicare descriptors. Public clinic criteria and laboratory prices are not established here. A rebate does not necessarily mean a free test.</p><p>Family history alone has not been converted into a genetic risk score. Missing information is treated as unknown.</p></details><div class="actions"><button class="secondary" id="download">Download my summary ↓</button><button class="text-button" id="finish-reset">Start again</button></div>`}
function render(){
 if(step==='home')app.innerHTML=`<section class="hero"><div><div class="eyebrow">MADE FOR YOUR NEXT STEP</div><h1>Your questions.<br>Your genetics.<br>A place to start.</h1><p class="intro muted">Explore genetic testing that may be relevant to you—and the pathways that could help you access it.</p><button class="primary" id="begin">Explore my options <span>↗</span></button><p class="muted intro-note">A few questions. No account needed.</p></div><div class="art" aria-hidden="true"><div class="rings"><i></i><i></i><i></i></div><h2>A little clarity.<br>A next step<br>made for you.</h2><small>YOUR STORY IS THE STARTING POINT.</small></div></section><div class="trust"><span>◌ Guided by your personal and family history</span><span>◌ Answers stay in this browser tab</span><span>◌ A starting point for a GC conversation</span></div><div class="notice">This prototype explores <strong>hereditary breast cancer and reproductive genetics</strong>—carrier screening, NIPT and karyotyping. Other interests can be selected, but their detailed pathways are not built yet.</div>`;
 if(step==='goal')app.innerHTML=shell('What brings you here?','Choose the main thing you’d like help understanding.',opts('goal',[['family','A condition in my family','Understand an inherited risk'],['health','My own health','Explore a diagnosis or health concern'],['pregnancy','Pregnancy, fertility or family planning','Explore reproductive testing'],['medication','Medication response','Understand genetic testing for medicines'],['general','General health or screening','Explore what testing could tell me'],['unsure','I’m not sure yet','Help me find a starting point']]));
 if(step==='interest')app.innerHTML=shell('Anything specific in mind?','Choose a condition or area. You don’t need to know the name of a genetic test.',opts('interest',[['breast','Breast cancer','Inherited risk · BRCA and related testing'],['cancer','Another inherited cancer'],['reproductive','Reproductive testing','Carrier screening, NIPT and karyotyping'],['carrier','Carrier screening'],['nipt','NIPT / prenatal screening'],['karyotype','Karyotyping / chromosome testing'],['heart','Heart or cholesterol conditions'],['rare','Rare or undiagnosed conditions'],['pgx','Medication-response testing'],['other','Something else'],['unsure','I don’t have a test in mind']]));
 if(step==='clarify')app.innerHTML=shell('Where would you like to begin?','Choose a starting point. We can explore breast cancer or reproductive genetics, or help you prepare for a broader conversation.',opts('clarification',[['breast','Breast cancer in me or my family'],['reproductive','Pregnancy, fertility or family planning'],['general','A broader genetics conversation']]));
 if(step==='who')app.innerHTML=shell('Who are you exploring for?','The detailed prototype supports adults answering for themselves in Australia.',opts('forWhom',[['myself','Myself'],['child','My child'],['other','Someone else']])+field('Age of the person being considered','age','number','min="0" max="120" inputmode="numeric"')+sel('Where do they live?','location',[['','Select a location'],['Australia','Australia'],['Other','Outside Australia'],['Unknown','Not sure']],a.location));
 if(step==='diagnosis')app.innerHTML=shell('Have you had breast cancer?','This helps distinguish testing after a diagnosis from testing for an inherited family risk.',opts('diagnosis',standard)+(a.diagnosis==='yes'?field('Age at diagnosis, if known','diagnosisAge','number','min="0" max="120"'):'')+'<div class="notice">Looking for a mammogram or concerned about a new breast change? This genetic testing explorer cannot assess that. Please discuss it with your healthcare professional.</div>',2);
 if(step==='family')app.innerHTML=shell('Has anyone in your biological family had cancer?','Include both sides of your family. Details about relatives who have died can still be recorded. Unknown ages are okay.',opts('familyStatus',standard)+(a.familyStatus==='yes'?relatives()+'<button class="secondary" id="add-relative">+ Add a relative</button>':''),2);
 if(step==='variant')app.innerHTML=shell('Has an inherited gene variant been found in your family?','For example, a confirmed BRCA1 or BRCA2 result. A cancer diagnosis by itself does not tell us whether a variant was found.',opts('variant',[['yes','Yes, an inherited variant was confirmed'],['no','No known inherited variant'],['unknown','I’m not sure / reports aren’t available']]),2);
 if(step==='prior')app.innerHTML=shell('Have you had genetic testing before?','Previous testing can affect which test or funding pathway is relevant. A mammogram is not a genetic test.',opts('prior',standard),2);
 if(step==='review')app.innerHTML=shell('Does this look right?','Check your answers before exploring possible pathways. Nothing is sent to a clinic.',`<div class="summary"><ul>${facts().map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><p class="muted">The result uses the supplied research catalogue. It does not confirm eligibility, choose a test for you or guarantee funding.</p>`,3);
 if(step==='result')app.innerHTML=result();
 if(step.startsWith('repro-'))app.innerHTML=reproductiveScreen();
 if(step==='unavailable')app.innerHTML=`<div class="compact"><span class="pill">YOUR STARTING POINT</span><h1 tabindex="-1">You don’t need to have a test in mind.</h1><p class="muted">A genetic counsellor can help clarify your question and whether genetic testing might be useful.</p><div class="notice">This area isn’t assessed in the prototype yet. That does not mean testing or funding is unavailable.</div><div class="consult"><div><h2>Start with a conversation.</h2><p>Talk through your goals, family history and possible next steps.</p></div><button class="primary" id="consult">Consultation preview ↗</button></div><div class="actions"><button class="text-button" id="back">← Back</button><button class="secondary" id="try-breast">Explore breast cancer</button></div></div>`;
 bind();
}
function error(t){document.querySelector('#error').textContent=t}
const sequence=['home','goal','interest','who','diagnosis','family','variant','prior','review','result'];
function next(){
 if(step.startsWith('repro-')){const message=validateReproductive(step,a);if(message)return error(message);const route=reproductiveSteps(a);return go(route[route.indexOf(step)+1]);}
 if(step==='goal'){if(!a.goal)return error('Choose an option, including “I’m not sure”.');return go('interest')}
 if(step==='interest'){if(!a.interest)return error('Choose an area or “I don’t have a test in mind”.');const r=nextRoute(a);if(r==='reproductive'&&a.interest!=='reproductive')a.reproFocus=a.interest;return go(['breast','reproductive'].includes(r)?'who':r)}
 if(step==='clarify'){if(!a.clarification)return error('Choose where you’d like to begin.');if(['breast','reproductive'].includes(a.clarification)){a.interest=a.clarification;return go('who')}return go('unavailable')}
 if(step==='who'){if(!a.forWhom||a.age===''||!a.location)return error('Please add who this is for, an age and a location.');if(!Number.isInteger(Number(a.age))||Number(a.age)<0||Number(a.age)>120)return error('Please enter an age between 0 and 120.');if(a.forWhom!=='myself'||Number(a.age)<18||a.location!=='Australia')return go(isReproductive(a)?'repro-result':'result');if(isReproductive(a))return go('repro-focus')}
 if(step==='diagnosis'){if(!a.diagnosis)return error('Please select an answer.');if(a.diagnosisAge && (Number(a.diagnosisAge)<0||Number(a.diagnosisAge)>Number(a.age)))return error('Age at diagnosis cannot exceed your current age.')}
 if(step==='family'){if(!a.familyStatus)return error('Please select an answer.');if(a.familyStatus==='yes'&&(!a.relatives.length||a.relatives.some(r=>!r.relationship||!r.side||!r.cancer)))return error('Add at least one relative and choose the relationship, side and cancer type. “Not sure” is available.');if(a.relatives.some(r=>r.age!==''&&(!Number.isInteger(Number(r.age))||Number(r.age)<0||Number(r.age)>120)))return error('Use an age between 0 and 120, or leave it blank.')}
 if(step==='variant'&&!a.variant)return error('Please select an answer.');if(step==='prior'&&!a.prior)return error('Please select an answer.');go(sequence[sequence.indexOf(step)+1]);
}
function back(){if(step.startsWith('repro-')){const route=reproductiveSteps(a);return go(route[Math.max(0,route.indexOf(step)-1)]);}if(['clarify','unavailable','who'].includes(step))return go('interest');go(sequence[Math.max(0,sequence.indexOf(step)-1)])}
function modal(content){document.querySelector('#modal-content').innerHTML=content;document.querySelector('#modal').showModal()}
function reset(){a=initial();go('home')}
function download(){if(isReproductive(a)){const r=assessReproductive(a);return saveSummary(`MADE GENETICS — REPRODUCTIVE CONSULTATION SUMMARY\nPossible pathways, not confirmed eligibility\n\n${facts().join('\n')}\n\n${r.priority}\n${r.tests.map(t=>`${t.name}\n${t.description}\n${t.relevance}\nFunding: ${t.funding}\n${t.extra}`).join('\n\n')}\n\nPublic pathway: ${r.public}\n\nTo clarify:\n${r.flags.join('\n')}\n\nSource rules: ${r.refs.join(', ')||'Outside assessed scope'}. Supplied catalogue dated 7 October 2026; not independently verified current guidance.\nNo booking or referral has been submitted.\n`);}const r=assess(a);const text=`MADE GENETICS — CONSULTATION SUMMARY\nPrototype: document-based pathways, not confirmed eligibility\n\n${facts().join('\n')}\n\nMedicare: ${r.medicare}\nPublic services: ${r.public}\nPrivate: ${r.private}\n\nTo clarify:\n${r.flags.join('\n')}\n\nSource rules: ${r.refs.join(', ')}. Supplied catalogue dated 7 October 2026; not independently verified current guidance.\nNo booking or referral has been submitted.\n`;saveSummary(text)}
function saveSummary(text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download='made-genetics-summary.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function bind(){app.querySelectorAll('[data-key]').forEach(el=>el.onclick=()=>{a[el.dataset.key]=el.dataset.value;if(el.dataset.key==='reproStage'&&el.dataset.value!=='pregnant'){a.reproWeeks='';a.pregnancyFinding='';}if(el.dataset.key==='reproFamily'&&el.dataset.value!=='yes')a.reproFamilyDetail='';if(el.dataset.key==='familyStatus'&&el.dataset.value!=='yes')a.relatives=[];if(el.dataset.key==='diagnosis'&&el.dataset.value!=='yes')a.diagnosisAge='';render()});app.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>{const k=el.dataset.field;if(k.startsWith('r')&&k.includes('.')){const [i,f]=k.slice(1).split('.');a.relatives[Number(i)][f]=el.value}else a[k]=el.value});
const on=(id,fn)=>{const e=document.getElementById(id);if(e)e.onclick=fn};on('begin',()=>go('goal'));on('next',next);on('back',back);on('add-relative',()=>{a.relatives.push({relationship:'',side:'',cancer:'',age:''});render()});app.querySelectorAll('[data-remove]').forEach(e=>e.onclick=()=>{a.relatives.splice(Number(e.dataset.remove),1);render()});on('edit',()=>go('who'));on('try-breast',()=>{a.interest='breast';go('who')});on('download',download);on('finish-reset',reset);on('consult',()=>modal('<span class="pill">CONSULTATION PREVIEW</span><h2>A next step with a genetic counsellor.</h2><p>A consultation can help review your family history, discuss testing and clarify referral or funding options.</p><div class="notice">Booking is not connected in this prototype. No appointment or referral has been made, and no answers have been sent.</div><p>Consultation fees and the booking service will be shown here once confirmed.</p>'));
}
document.getElementById('restart').onclick=()=>modal('<h2>Start again?</h2><p>This will clear the answers in this tab.</p><button class="primary" id="confirm-reset">Clear and restart</button>');document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='confirm-reset'){document.getElementById('modal').close();reset()}});document.getElementById('close-modal').onclick=()=>document.getElementById('modal').close();document.getElementById('privacy').onclick=()=>modal('<h2>Your answers stay with you.</h2><p>This prototype holds answers only in this tab’s memory. It does not send them to a server, save them in browser storage or include them in the address bar. Refreshing or closing the page clears them.</p><p>If you download a summary, it contains the health details you entered. It stays wherever you save it. Standard hosting access logs may record page requests, but the app does not send your answers.</p>');render();

function reproductiveScreen(){
 if(step==='repro-focus')return shell('Which options would you like to explore?','These tests answer different questions. You can explore them together, or focus on one.',opts('reproFocus',[['carrier','Carrier screening','Inherited conditions in prospective parents'],['nipt','NIPT','Chromosome screening during pregnancy'],['karyotype','Karyotyping','Chromosome assessment for a specific clinical question'],['all','All three areas'],['unsure','I’m not sure','Help me understand the differences']]),2);
 if(step==='repro-stage')return shell('What is your situation?','Choose the closest fit. You don’t need to share details of a pregnancy loss here.',opts('reproStage',[['planning','Planning a pregnancy'],['pregnant','An existing pregnancy'],['fertility','Fertility investigations or IVF'],['loss','After a pregnancy loss'],['general','Exploring for the future'],['unknown','I’m not sure']])+`<h3>Your role</h3>`+opts('reproRole',[['self','I am pregnant or may carry a pregnancy'],['partner','I am the reproductive partner'],['unknown','Unsure / another situation']])+(a.reproStage==='pregnant'?field('Pregnancy weeks, if known','reproWeeks','number','min="1" max="45" step="0.1" placeholder="Leave blank if unsure"'):''),2);
 if(step==='repro-carrier')return shell('A little about carrier screening','Previous results help distinguish a first screen, repeat testing and partner follow-up.',`<h3>Have you had carrier screening before?</h3>`+opts('carrierPrior',standard)+`<h3>Does your reproductive partner have a confirmed carrier result?</h3>`+opts('partnerCarrier',[['cf','Cystic fibrosis (CFTR)'],['sma','Spinal muscular atrophy (SMN1)'],['fxs','Fragile X (FMR1)'],['other','Another condition'],['none','No known carrier result'],['unknown','Not sure / not applicable']])+`<h3>Is there a known inherited condition or variant in your family?</h3>`+opts('reproFamily',standard)+(a.reproFamily==='yes'?field('Condition or gene, if known (optional)','reproFamilyDetail','text','maxlength="200"'):'')+`<h3>Do you have Ashkenazi Jewish ancestry?</h3><p class="muted">The supplied documents describe a separate carrier-screening pathway for this ancestry. You can choose “I’m not sure” or prefer not to say.</p>`+opts('reproAncestry',[['yes','Yes'],['no','No'],['unknown','Not sure / prefer not to say']]),2);
 if(step==='repro-pregnancy')return shell('About prenatal screening',a.reproStage==='pregnant'?'Have you received a screening or ultrasound result in this pregnancy? Choose the result you most want to discuss.':'NIPT is for an existing pregnancy. We can show you information for planning ahead, but cannot establish that testing is appropriate now.',a.reproStage==='pregnant'?opts('pregnancyFinding',[['notdone','No screening result yet'],['low','A lower-chance screening result'],['high','A higher-chance screening result'],['inconclusive','An inconclusive / no-result screen'],['scan','An ultrasound finding needing review'],['unknown','I’m not sure']])+`<div class="notice">This explorer does not interpret screening or scan results. A report needing review should be discussed with your maternity team.</div>`:`<div class="notice">NIPT, carrier screening and karyotyping are different tests. A GC can help explain which question each answers.</div>`,2);
 if(step==='repro-chromosome')return shell('What prompted the chromosome-testing question?','We’ll keep parental karyotyping, testing after a pregnancy loss and fetal diagnostic testing separate.',opts('karyoReason',[['miscarriage','One or more pregnancy losses'],['infertility','Fertility investigations'],['rearrangement','A known chromosome rearrangement','In me, my partner or my family'],['prenatal','A chromosome test during pregnancy'],['requested','A clinician suggested karyotyping'],['curious','General information'],['unknown','I’m not sure']])+`<h3>Have you or your partner had chromosome testing before?</h3>`+opts('karyoPrior',standard),2);
 if(step==='repro-review')return shell('Does this look right?','Check your answers before exploring possible tests and funding routes.',`<div class="summary"><ul>${facts().map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><p class="muted">This is a starting point for a GC conversation. No information is sent to a clinic.</p>`,3);
 const r=assessReproductive(a);
 return `<div class="result-head"><span class="pill">POSSIBLE PATHWAYS · NOT AN ELIGIBILITY DECISION</span><h1 tabindex="-1">${r.headline}</h1><p class="muted">Different tests answer different questions. These options are for discussion with a genetic counsellor or your treating clinician.</p></div>${r.priority?`<div class="notice"><strong>Discuss your pregnancy report</strong><br>${r.priority}</div>`:''}${!r.scope?`<div class="notice">${r.flags[0]}</div>`:''}<div class="repro-results">${r.tests.map(t=>`<article class="card"><span class="number">${t.tag}</span><h2>${t.name}</h2><p>${t.description}</p><div class="test-detail"><section><h3>How it relates to your answers</h3><p>${t.relevance}</p></section><section><h3>Possible funding</h3><p>${t.funding}</p></section></div><p class="muted">${t.extra}</p></article>`).join('')}</div><div class="summary"><h3>Could a public service help?</h3><p>${r.public}</p></div><div class="consult"><div><h2>A next step, made for you.</h2><p>A GC can help you compare tests, understand existing reports and clarify funding or referral options.</p></div><button class="primary" id="consult">Talk to a genetic counsellor ↗</button></div><div class="summary"><h3>What to clarify with your clinician or GC</h3><ul>${r.flags.map(x=>`<li>${x}</li>`).join('')}</ul></div><details open><summary>Your answers</summary><ul>${facts().map(x=>`<li>${esc(x)}</li>`).join('')}</ul><button class="text-button" id="edit">Edit answers</button></details><details><summary>Where this guidance comes from</summary><p>Supplied eligibility catalogue dated 7 October 2026: ${r.refs.join(', ')||'No funding assessment outside prototype scope'}. Test catalogue entries include AUGT-001/002 (carrier screens), AUGT-009 (NIPT), AUGT-014/017/021 (prenatal, pregnancy-loss and parental chromosome testing).</p><p>These summaries have not been independently verified against current descriptors. The karyotype rules are incomplete, and requester information is inconsistent in the source set. A rebate does not necessarily mean a free test. No current prices are quoted.</p></details><div class="actions"><button class="secondary" id="download">Download my summary ↓</button><button class="text-button" id="finish-reset">Start again</button></div>`;
}
