import {services} from './services.js';
const root=document.querySelector('#booking');
const selected=new URLSearchParams(location.search).get('service');
const id=Object.hasOwn(services,selected)?selected:'navigator';
const service=services[id];
let mode='',finished=false,date='',time='';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=new Date();const minDate=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
function render(){
 root.innerHTML=`<div class="booking-layout"><section><a class="text-button" href="booking.html?service=${id==='gc'?'navigator':'gc'}">Explore the ${id==='gc'?'20-minute Genetic Navigator':'45-minute GC Consultation'} instead →</a><p class="eyebrow">A CONVERSATION WITH A GENETIC COUNSELLOR</p><h1 tabindex="-1">${service.name}</h1><span class="pill">${service.duration} MINUTES</span><p class="intro">${service.description}</p><ul>${service.points.map(p=>`<li>${p}</li>`).join('')}</ul><p>A clearer answer may depend on reviewing medical reports or a specialist assessment. A referral or funded test cannot be guaranteed.</p><div class="notice"><strong>Consultation fee: to be confirmed</strong><br>The final fee will be shown before a real booking or waiting-room entry. No payment is taken in this sample.</div></section><section class="booking-panel"><span class="eyebrow">SAMPLE BOOKING EXPERIENCE</span>${finished?confirmation():`<h2>How would you like to connect?</h2><p>Choose an appointment or explore the waiting room.</p><div class="options"><button class="option ${mode==='appointment'?'selected':''}" data-mode="appointment" aria-pressed="${mode==='appointment'}"><span>Book an appointment<small>Choose a time that suits you</small></span></button><button class="option ${mode==='waiting'?'selected':''}" data-mode="waiting" aria-pressed="${mode==='waiting'}"><span>Join the waiting room<small>See how joining for the next available GC would work</small></span></button></div>${mode==='appointment'?`<h3>Choose an example appointment</h3><p>These sample times are illustrative, not live availability. Times are shown in Melbourne time.</p><label class="field">Preferred date<input id="date" type="date" min="${minDate}" value="${escape(date)}"></label><label class="field">Example time<select id="time"><option value="">Choose a time</option>${['09:00','11:00','14:00'].map(t=>`<option ${time===t?'selected':''}>${t}</option>`).join('')}</select></label><p id="booking-error" class="error" role="alert"></p><button class="primary" id="confirm">Preview appointment booking →</button>`:mode==='waiting'?`<h3>Your place to start</h3><p>In the live service, you would see GC availability and the estimated wait before joining.</p><div class="notice">This sample is not connected to a live waiting room. No clinician is online through this page and no queue position is assigned.</div><button class="primary" id="confirm">Preview joining the waiting room →</button>`:''}<p class="muted">Your explorer answers are not transferred. This sample does not collect contact details or notify a clinician.</p>`}</section></div>`;
 root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render()});
 root.querySelector('#date')?.addEventListener('input',e=>date=e.target.value);
 root.querySelector('#time')?.addEventListener('change',e=>time=e.target.value);
 root.querySelector('#confirm')?.addEventListener('click',()=>{if(mode==='appointment'&&(!date||date<minDate||!time)){root.querySelector('#booking-error').textContent='Choose today or a future date and an example time.';return;}finished=true;render();root.querySelector('h2')?.focus();});
 root.querySelector('#again')?.addEventListener('click',()=>{finished=false;render()});
}
function confirmation(){return `<span class="pill">PREVIEW COMPLETE</span><h2 tabindex="-1">${mode==='appointment'?'Your sample appointment':'Your sample waiting room'}</h2><p><strong>${service.name} · ${service.duration} minutes</strong></p>${mode==='appointment'?`<p>${escape(date)} at ${escape(time)} · Melbourne time</p><div class="notice">No appointment has been booked. In the live service, you would confirm your details and fee before receiving a booking confirmation and joining instructions.</div>`:`<div class="notice">You have not joined a live queue. In the live service, this page would show your waiting-room status and instructions for connecting with your GC.</div>`}<p>No payment, referral or message to a clinician has been made.</p><button class="secondary" id="again">Explore another booking option</button>`}
render();
