const mbs=n=>({label:`Medicare item ${n}`,url:`https://www9.health.gov.au/mbs/fullDisplay.cfm?type=item&q=${n}&qt=item`});
export function fundingFor(id,a={},scope=true){
 const medicare={channel:'Medicare',status:'May be funded — assessment required',summary:'A Medicare rebate does not necessarily cover the full fee.',criteria:[],sources:[]};
 if(id==='breast')Object.assign(medicare,{summary:a.variant==='yes'?'A confirmed family variant may support the family-testing pathway. The actual report is needed.':a.diagnosis==='yes'?'Testing after a cancer diagnosis may qualify if the specialist assesses a sufficient chance of an inherited variant.':'Family history can justify assessment, but does not by itself establish Medicare eligibility.',criteria:[
 'Panel testing (73296): you have breast, ovarian, fallopian tube or primary peritoneal cancer, and your clinical and family history indicate a greater than 10% chance of a harmful inherited variant. This is not your lifetime chance of developing cancer.',
 'The panel must include BRCA1 and BRCA2 and at least one other relevant gene. A specialist or consultant physician must request it. Limit: once per cancer diagnosis.',
 'Family-variant testing (73297): a biological relative has a confirmed harmful or likely harmful variant in a relevant gene. A specialist or consultant physician must request your test.',
 'For 73297, you must not previously have received testing under 73295, 73296 or 73302. Limit: once per variant. Pre-test counselling and written informed consent are required.'
 ],sources:[mbs(73296),mbs(73297)]});
 if(id==='carrier')Object.assign(medicare,{summary:'Medicare can support the three-condition screen and specific partner follow-up. Expanded panels are not funded under these two items.',criteria:[
 'First screen (73451): you are pregnant or planning pregnancy. The screen checks cystic fibrosis (CFTR), spinal muscular atrophy (SMN1) and fragile X (FMR1).',
 'Your clinician must confirm who should have the first screen, including whether an FMR1 variant could be passed on to cause fragile X in a child. Your reproductive role and genetic circumstances matter.',
 '73451 is limited to one test per lifetime. It cannot be billed in association with items 73300, 73305 or 73345–73350; your clinician or laboratory can check previous or associated tests.',
 'Partner follow-up (73452): your reproductive partner was found to carry a harmful or likely harmful CFTR or SMN1 variant through 73451. This checks the couple’s risk of CF or SMA; it does not cover FMR1 partner follow-up.',
 '73452 is limited to one test per condition per lifetime. The first person’s result must be available before partner testing.'
 ],sources:[mbs(73451),mbs(73452)]});
 if(id==='nipt')Object.assign(medicare,{status:'Not funded — standard NIPT',summary:'The supplied funding catalogue lists standard chromosome-screening NIPT as self-funded, with no Medicare rebate.',criteria:['There are no Medicare eligibility criteria for standard NIPT in the supplied catalogue. Separately funded fetal RhD blood-group testing is a different test.']});
 if(id==='karyotype')Object.assign(medicare,{summary:'Medicare chromosome-testing items exist. A clinician and laboratory must confirm the right test, clinical reason, sample and billing requirements.',criteria:[
 '73289 describes examination of all chromosomes using a blood sample. This may be relevant to parental blood karyotyping.',
 '73287 describes examination of all chromosomes in tissue or fluid other than blood. It cannot be billed together with 73388.',
 '73293 describes chromosome-region testing of fresh pregnancy-loss tissue, excluding maternal-cell contamination. This is different from a parent’s blood karyotype.',
 'These item descriptions do not specify an age cutoff or required number of miscarriages. We cannot turn your answers into a confirmed entitlement. Sample collection or pregnancy procedures may have separate fees.'
 ],sources:[mbs(73289),mbs(73287),mbs(73293)]});
 const insurance={channel:'Private health insurance',status:'Not funded — standard outpatient cover',summary:'Standard private health insurance does not cover out-of-hospital medical tests of this kind. Do not assume extras cover will pay for testing.',criteria:['Cover may differ for eligible testing during an admitted hospital stay, subject to the Medicare item and your policy. Ask your insurer; a gap may still apply.'],sources:[{label:'Australian Government: private health cover',url:'https://privatehealth.gov.au/health_insurance/what_is_covered/privatehealth.htm'}]};
 const publicService={channel:'Public services',status:'May be free — referral and acceptance required',summary:'A public genetics service may provide a free assessment and clinically indicated testing if your referral is accepted. Waiting lists can be long.',criteria:[id==='nipt'?'A public consultation does not guarantee free NIPT. The supplied documents do not establish a routine free NIPT pathway.':'Acceptance and test funding depend on the service, clinical need and local criteria.','Chat with our genetic counsellor to understand waiting lists in your area and the referral required.'],action:'gc',sources:[]};
 const prices={breast:'Indicative hereditary cancer panel fee: A$400–$800. A targeted test for a known family variant needs its own quote.',carrier:'Indicative examples span A$385–$595 per person: approximately A$385 for a three-condition screen and A$595 for expanded screening. These are different panels, not a national minimum and maximum.',nipt:'Indicative NIPT fee: A$400–$800 per pregnancy, depending on the panel and provider.',karyotype:'Quote required: the supplied documents do not provide a reliable private karyotyping fee range.'};
 const privateTest={channel:'Private testing',status:'Available — out-of-pocket fee',summary:prices[id],criteria:[id==='carrier'?'Carrier prices are historical examples (January 2024) in the supplied research; obtain a current quote.':'Prices, where shown, are indicative figures from the supplied research, not current provider quotes.','Confirm whether consultation, sample collection and any procedures are included. Testing remains subject to clinical suitability and request requirements.','Chat with our genetic navigator to find an appropriate test, compare prices and help organise a referral.'],action:'navigator',sources:[]};
 if(!scope){medicare.status='Not assessed';insurance.status='Not assessed';publicService.status='Not assessed';privateTest.status='Quote and assessment required';for(const s of [medicare,insurance,publicService]){s.summary='This prototype assesses adults answering for themselves in Australia. A tailored consultation is needed.';s.criteria=[];}privateTest.summary='Fees and access need individual confirmation.';}
 return [medicare,insurance,publicService,privateTest];
}
export const fundingText=(id,a,scope=true)=>fundingFor(id,a,scope).map(s=>`${s.channel}: ${s.status}\n${s.summary}\n${s.criteria.join('\n')}\n${s.sources.map(x=>`${x.label}: ${x.url}`).join('\n')}`).join('\n\n');
