// Generated from the supplied v2 plain-language catalogue; normalised source version 2.1.
export const medicareItems={
  "73296": {
    "item": "73296",
    "test_name_plain": "Testing for gene changes linked to breast, ovarian, fallopian tube or primary peritoneal cancer",
    "what_test_checks_plain": "This test checks for gene changes linked to these cancers in a person’s genetic information, not just in a tumour. It must include BRCA1 and BRCA2 and at least one other relevant gene. It may also check for missing or extra copies of DNA where appropriate. A known or likely disease-causing change is one known, or strongly believed, to cause disease. This does not include every gene change or a change whose effect is uncertain.",
    "who_may_qualify_plain": "A person diagnosed with breast, ovarian, fallopian tube or primary peritoneal cancer may qualify if their clinical and family history puts them at greater than 10% risk of having a relevant known or likely disease-causing gene change.",
    "eligibility_requirements_plain": "1. The patient has a diagnosis of breast cancer, ovarian cancer, fallopian tube cancer or primary peritoneal cancer; AND 2. their clinical and family history criteria place them at greater than 10% risk of having a known or likely disease-causing gene change associated with breast, ovarian, fallopian tube or primary peritoneal cancer; AND 3. the test checks the patient’s genetic information, not just a tumour, for changes in BRCA1 and BRCA2 and one or more other relevant genes, including missing or extra copies of DNA where appropriate; AND 4. a specialist or consultant physician requests the test. The service is allowed once per cancer diagnosis.",
    "who_can_order_plain": "A specialist or consultant physician must request the test. The item does not specify a particular specialty.",
    "previous_testing_and_repeat_limits_plain": "The service is allowed once per cancer diagnosis. The item does not state a separate restriction based on previous testing or any other item-specific repeat limit. General pathology rules may still apply.",
    "important_exclusions_plain": "A diagnosis of one of the listed cancers is required; suspicion alone is not enough. The risk threshold is greater than 10%, not 10% or greater. The item does not specify a sample type, a prerequisite investigation or a requirement to link the test to another MBS item. It does not state a pre-test consent or counselling requirement. Under the associated note, patients found to have any form of affected allele should be referred for post-test genetic counselling, as the result may have implications for family members.",
    "clinician_notes_plain": "The test must check germline gene variants, meaning gene changes in the patient’s genetic information rather than only in a tumour. It must include BRCA1 and BRCA2 and one or more other relevant genes associated with breast, ovarian, fallopian tube or primary peritoneal cancer. It must include copy number variation, such as missing or extra copies of DNA, where appropriate. PN.0.23 applies to item 73296: patients found to have any form of affected allele should be referred for post-test genetic counselling. Counselling may be provided by the treating specialist or a genetic counselling service, or by a clinical geneticist on referral. PN.0.23’s written informed consent and counselling-before-testing instructions list other items, not item 73296.",
    "source_url": "https://www9.health.gov.au/mbs/fullDisplay.cfm?type=item&q=73296&qt=item",
    "review_status": "Source-reviewed plain-language draft; clinical and billing sign-off required"
  },
  "73297": {
    "item": "73297",
    "test_name_plain": "Gene testing for breast, ovarian, fallopian tube and primary peritoneal cancer",
    "what_test_checks_plain": "The test looks for gene changes in the patient’s inherited DNA that are linked to breast, ovarian, fallopian tube or primary peritoneal cancer. It may include a check for missing or extra sections of DNA, where appropriate.",
    "who_may_qualify_plain": "A patient may meet the criteria if a biological relative has had a disease-causing or likely disease-causing change identified in a relevant gene, and the other requirements are met.",
    "eligibility_requirements_plain": "1. A specialist or consultant physician requests testing for gene changes linked to breast, ovarian, fallopian tube or primary peritoneal cancer. The genes may include BRCA1 or BRCA2 and one or more other relevant genes. 2. The patient has a biological relative who has had a disease-causing or likely disease-causing gene change identified in one or more of those genes. 3. The patient has not previously received a service covered by item 73295, 73296 or 73302. 4. The service is limited to once per variant. Before ordering, the practitioner should ensure that the patient or their proxy has given written informed consent. Testing should only be performed after genetic counselling.",
    "who_can_order_plain": "A specialist or consultant physician can request the service. The item does not specify a particular specialty.",
    "previous_testing_and_repeat_limits_plain": "The patient must not previously have received a service covered by item 73295, 73296 or 73302. The service is limited to once per variant.",
    "important_exclusions_plain": "The item does not specify an age, a minimum degree of biological relationship, or a requirement for the patient to have cancer. No other item-specific billing exclusions are stated in the supplied material.",
    "clinician_notes_plain": "Item 73297 is for testing gene changes in a patient’s inherited DNA, including copy-number changes where appropriate. The genes must be associated with breast, ovarian, fallopian tube or primary peritoneal cancer. They may include BRCA1 or BRCA2 and one or more other relevant genes. The patient must have a biological relative with a known or likely disease-causing variant identified in one or more of those genes. A known or likely disease-causing variant is a gene change known or likely to cause disease; it is not simply any gene change or a variant of uncertain significance. The test must be requested by a specialist or consultant physician. Under PN.0.23, before ordering, the practitioner should ensure that the patient or their proxy has given written informed consent. Testing should only be performed after genetic counselling. Counselling may be provided by the treating specialist, a genetic counselling service or a clinical geneticist on referral. Further counselling may be needed after the results. The patient must not previously have received a service covered by item 73295, 73296 or 73302, and the service is limited to once per variant.",
    "source_url": "https://www9.health.gov.au/mbs/fullDisplay.cfm?type=item&q=73297&qt=item",
    "review_status": "Source-reviewed plain-language draft; clinical and billing sign-off required"
  },
  "73451": {
    "item": "73451",
    "test_name_plain": "Carrier screening for cystic fibrosis, spinal muscular atrophy and fragile X before or during pregnancy",
    "what_test_checks_plain": "This test checks whether you carry a disease-related change in the CFTR, SMN1 or FMR1 gene. Being a carrier does not necessarily mean you have the condition. The result helps assess the chance of a child having the condition.",
    "who_may_qualify_plain": "You may qualify if you are pregnant or planning a pregnancy. For fragile X testing, the explanatory note says the person tested must be the pregnant or pregnancy-planning patient who, if found to carry a relevant FMR1 gene change, could pass on a change that may cause fragile X syndrome in their child.",
    "eligibility_requirements_plain": "1. You are pregnant or planning a pregnancy. 2. The test checks your carrier status for one of the following: (a) a known or likely disease-causing change in the CFTR gene to assess reproductive risk of cystic fibrosis; OR (b) a known or likely disease-causing change in the SMN1 gene to assess reproductive risk of spinal muscular atrophy; OR (c) a known or likely disease-causing change in the FMR1 gene to assess reproductive risk of fragile X syndrome. 3. The service is not associated with a service covered by item 73300, 73305, 73345, 73346, 73347, 73348, 73349 or 73350. 4. Medicare allows one test under this item per lifetime. For fragile X testing, the explanatory note says the person tested first must be the pregnant or pregnancy-planning patient who, if found to carry a relevant FMR1 change, could pass on a change that may cause fragile X syndrome in their child. Any eligible partner follow-up under item 73452 can occur only after that patient has been tested.",
    "who_can_order_plain": "Item 73451 does not specify a required medical specialty for the requesting doctor. The clinician and laboratory should confirm that the request meets the usual Medicare pathology requirements.",
    "previous_testing_and_repeat_limits_plain": "Medicare allows one test under item 73451 per lifetime, not a new test for each pregnancy. Services associated with items 73300, 73305, 73345, 73346, 73347, 73348, 73349 or 73350 are excluded from this item.",
    "important_exclusions_plain": "This item does not apply to a service associated with a service covered by item 73300, 73305, 73345, 73346, 73347, 73348, 73349 or 73350. The test is limited to one per lifetime.",
    "clinician_notes_plain": "This item covers carrier testing of the cystic fibrosis transmembrane conductance regulator (CFTR) gene for cystic fibrosis, the survival motor neuron 1 (SMN1) gene for spinal muscular atrophy, or the fragile X messenger ribonucleoprotein 1 (FMR1) gene for fragile X syndrome. Explanatory note PN.7.16 says that for fragile X testing, the patient tested under item 73451 is the pregnant or pregnancy-planning patient who, if found to carry a relevant FMR1 change, could pass on a change that may cause fragile X syndrome in their child. The patient's pregnancy partner may be tested under item 73452 only after the patient under item 73451 has been tested. Item 73452 is not the item described here. The laboratory should use a method suitable for the clinical setting, with enough diagnostic range and sensitivity to detect at least 95% of disease-causing gene changes likely to be present in the patient. Testing should include at least 50 of the CFTR variants most frequently found in the Australian population.",
    "source_url": "https://www9.health.gov.au/mbs/fullDisplay.cfm?type=item&q=73451&qt=item",
    "review_status": "Source-reviewed plain-language draft; clinical and billing sign-off required"
  },
  "73452": {
    "item": "73452",
    "test_name_plain": "Partner follow-up testing for cystic fibrosis or spinal muscular atrophy",
    "what_test_checks_plain": "This test checks whether your pregnancy partner has a relevant gene change after a change linked to cystic fibrosis or spinal muscular atrophy was found in your test. The results help assess the couple’s chance of having a child with that condition.",
    "who_may_qualify_plain": "You may qualify if you are the pregnancy partner of someone whose testing under MBS item 73451 found a disease-causing or likely disease-causing change in CFTR or SMN1.",
    "eligibility_requirements_plain": "All of these conditions must be met:\n1. Your pregnancy partner was tested under MBS item 73451.\n2. That test found a disease-causing or likely disease-causing change in CFTR, which is linked to cystic fibrosis, or SMN1, which is linked to spinal muscular atrophy. This means a gene change known or strongly believed to cause disease; it does not include every gene change or a change of uncertain significance.\n3. Your test is to assess the couple’s chance of having a child with the relevant condition.\n4. Medicare allows one test per condition per lifetime.",
    "who_can_order_plain": "The item descriptor does not specify a required medical specialty for the requester. The clinician and laboratory should confirm the usual Medicare pathology request requirements.",
    "previous_testing_and_repeat_limits_plain": "The person whose result identified the relevant CFTR or SMN1 change must have been tested under item 73451. The partner test is limited to one test per condition per lifetime.",
    "important_exclusions_plain": "The item descriptor covers CFTR and SMN1 testing for cystic fibrosis and spinal muscular atrophy. It does not cover a partner’s fragile X test or routine partner screening before the first person’s result. The supplied descriptor does not specify samples, age limits or other exclusions.",
    "clinician_notes_plain": "The item descriptor requires testing of the reproductive partner of a person whose item 73451 test found a known or likely disease-causing variant in CFTR or SMN1. A known or likely disease-causing variant is a gene change known or strongly believed to cause disease. The purpose is to assess the couple’s reproductive risk of cystic fibrosis or spinal muscular atrophy. The descriptor allows one test per condition per lifetime.\n\nPN.7.16 also describes item 73452 in an FMR1/fragile X context. It says the person tested under item 73451 is planning a pregnancy or is already pregnant, and their pregnancy partner is not at risk of passing on an FMR1 variant that would cause fragile X syndrome, whether or not that partner is a carrier. PN.7.16 says the person planning pregnancy or already pregnant must be tested first under item 73451. The supplied item descriptor names CFTR and SMN1, not FMR1, and the supplied material does not explain this difference.",
    "source_url": "https://www9.health.gov.au/mbs/fullDisplay.cfm?type=item&q=73452&qt=item",
    "review_status": "Source-reviewed plain-language draft; clinical and billing sign-off required"
  },
  "73289": {
    "item": "73289",
    "test_name_plain": "Whole-chromosome study on blood (MBS item 73289)",
    "what_test_checks_plain": "This study looks at the chromosomes in a blood sample. Chromosomes are structures that carry genetic information. The item descriptor does not say which chromosome changes the study can detect.",
    "who_may_qualify_plain": "The item descriptor does not specify which symptoms, diagnoses, ages, family histories or other clinical circumstances may qualify.",
    "eligibility_requirements_plain": "1. The study must cover the whole of every chromosome, using cytogenetic or other techniques. 2. It must be performed on blood. 3. It may involve one or more tests. 4. A service described in item 73293 is included if it is performed as part of the study.",
    "who_can_order_plain": "The item descriptor does not specify who must order the test. The clinician and laboratory should check the applicable request and billing requirements.",
    "previous_testing_and_repeat_limits_plain": "The supplied descriptor does not state a repeat limit for this item. Other applicable pathology rules may still apply.",
    "important_exclusions_plain": "The supplied descriptor does not state specific clinical or billing exclusions.",
    "clinician_notes_plain": "Item 73289 is in Group P7 (Genetics). It covers a study of the whole of every chromosome, using cytogenetic or other techniques, on a blood sample. One or more tests may be performed. A service described in item 73293 is included if it is performed as part of the study. The supplied information does not specify clinical indications, who may request the test, prerequisites, consent or counselling requirements.",
    "source_url": "https://www9.health.gov.au/mbs/fullDisplay.cfm?type=item&q=73289&qt=item",
    "review_status": "Source-reviewed plain-language draft; clinical and billing sign-off required"
  },
  "73287": {
    "item": "73287",
    "test_name_plain": "Test to examine all chromosomes in a non-blood sample (MBS item 73287).",
    "what_test_checks_plain": "The test examines the whole of every chromosome. Chromosomes are structures that contain genetic material. The sample must be tissue or fluid other than blood.",
    "who_may_qualify_plain": "The item does not specify who may qualify or set clinical indications or patient eligibility criteria. It describes the service and the sample it must use.",
    "eligibility_requirements_plain": "1. The service must examine the whole of every chromosome, using cytogenetic or another technique. 2. It must use one or more tissue or fluid samples other than blood, and may involve one or more tests. 3. A service described in item 73293 is included if performed. 4. The service must not be performed in conjunction with a service described in item 73388.",
    "who_can_order_plain": "The item does not specify which clinician may request the service. The ordering clinician and laboratory should check the applicable pathology request rules.",
    "previous_testing_and_repeat_limits_plain": "The item does not state a repeat limit or require previous testing.",
    "important_exclusions_plain": "Blood samples are excluded. Item 73287 does not apply if the service is performed in conjunction with a service described in item 73388.",
    "clinician_notes_plain": "Item 73287 covers a service that examines the whole of every chromosome by cytogenetic or another technique, using one or more tissue or fluid samples other than blood. It includes a service described in item 73293 if performed. Under restriction 2.7.1A in note PR.7.3, item 73287 applies only if the service is not performed in conjunction with a service described in item 73388. The supplied information does not state any clinical eligibility criteria, gene-variant or disease requirements, requester-specialty requirements, or consent or counselling requirements.",
    "source_url": "https://www9.health.gov.au/mbs/fullDisplay.cfm?type=item&q=73287&qt=item",
    "review_status": "Source-reviewed plain-language draft; clinical and billing sign-off required"
  },
  "73293": {
    "item": "73293",
    "test_name_plain": "Chromosome testing of fresh tissue from a pregnancy",
    "what_test_checks_plain": "The test checks chromosomes in fresh tissue from the products of conception for specific genetic changes. It also checks whether the sample contains cells from the pregnant person, as these could affect the results.",
    "who_may_qualify_plain": "This item is for diagnostic testing of products of conception. It does not state separate clinical eligibility criteria.",
    "eligibility_requirements_plain": "1. The sample must be fresh tissue from the products of conception. AND 2. The test must be a diagnostic study for specific constitutional genetic abnormalities. It must analyse one or more regions on all chromosomes and include a check for maternal cell contamination, which means cells from the pregnant person mixed into the sample. One or more tests are allowed. No other clinical thresholds or qualifying conditions are stated.",
    "who_can_order_plain": "The item does not specify a required medical specialty for the person ordering the test. The ordering clinician and laboratory should confirm any applicable rules for pathology requests.",
    "previous_testing_and_repeat_limits_plain": "The supplied item description does not state a repeat limit. General pathology rules may still apply.",
    "important_exclusions_plain": "The item specifies fresh tissue from the products of conception. It does not describe testing of other sample types or state any further exclusions.",
    "clinician_notes_plain": "MBS item 73293 is in Group P7 (Genetics). It covers analysis of one or more regions on all chromosomes for specific constitutional genetic abnormalities in fresh tissue from the products of conception. The test must include exclusion of maternal cell contamination. One or more tests are allowed. The supplied item information does not specify a required requester specialty, clinical thresholds, prerequisite investigations, consent or counselling requirements, or links to other MBS items.",
    "source_url": "https://www9.health.gov.au/mbs/fullDisplay.cfm?type=item&q=73293&qt=item",
    "review_status": "Source-reviewed plain-language draft; clinical and billing sign-off required"
  }
};
